spring.application.name=app

server.port=8090
spring.datasource.url=jdbc:postgresql://ep-odd-mountain-a2n2pt4g-pooler.eu-central-1.aws.neon.tech:5432/user-service?sslmode=require
spring.datasource.username=user-service_owner
spring.datasource.password=npg_sfKiJVlYyz13
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

jwt.secret=AGPE14jBBqUBy/1KAbCNCEuDh/TM5yU5C9yTrr3wbu4=
aes.secret=1234567891234567
logging.level.org.springframework.security=DEBUG